### PR TITLE
bump to 1.15.1

### PR DESCRIPTION
**Pull request by dougalsutherland**
Also do various recipe cleanups, including fixing the license: it's GPL 2, not 3, per the COPYING file in the source tarball.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
I guess `noarch: perl` isn't a thing yet, is it?

**Comment by dougalsutherland** [comment]
```
checking whether autoconf works... no
configure: error: The installed version of autoconf does not work.
```
...huh.

**Comment by dougalsutherland** [comment]
So I think this is because the `autoconf` packages don't have perl pinned, and they apparently don't work with 5.22. (#12 had the same failures.) Maybe would be fixed by just rerendering `autoconf` to make pinned versions; will send that PR now.

**Comment by dougalsutherland** [comment]
Closing/reopening to rebuild, now that https://github.com/conda-forge/autoconf-feedstock/pull/15 is available.

**Comment by dougalsutherland** [comment]
Apparently that doesn't actually rebuild on CircleCI, which is the one I can't just hit restart on anyway. :| Pushing an empty commit....

**Comment by ocefpaf** [comment]
Thanks @dougalsutherland!

**Pull request merged**
